#!/usr/bin/env python

import os
from subprocess import check_call

_dname = os.path.dirname

REPO_ROOT = _dname(_dname(os.path.abspath(__file__)))

check_call(['python', '-m', 'unittest',
            'discover'],shell=True)
